"""change workout DateTime to date

Revision ID: cb9b49e71133
Revises: 7422db416570
Create Date: 2026-04-11 16:06:44.939290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9b49e71133'
down_revision = '7422db416570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', recreate='always') as batch_op:
        batch_op.alter_column(
            'date',
            existing_type=sa.DateTime(),
            type_=sa.Date(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', recreate='always') as batch_op:
        batch_op.alter_column(
            'date',
            existing_type=sa.Date(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###
